name: Build and Test

on:
  push:
    branches:
      - main  # Set to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest  # Use an appropriate runner for your project

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x  # Use the desired .NET version

    - name: Restore and Build
      run: |
        dotnet restore
        dotnet build --configuration Release

    - name: Test
      run: dotnet test